### ISSUE TITLE
わからなかったこと

### ISSUE THREAD

**Issue by yukihamu1206** [yukihamu1206/twitter#1]
### Twitterクローンを作る第3回

**フォロー関連の処理**

### app/Http/Controllers/UsersController.php

#フォローする
**public function follow(User $user)**
{    
#自分
    $follower = auth()->user();
#フォローしているか確かめる
    $is_following = $follower->isFollowing($user->id);
    #フォローする　
    if(!$is_following){
        $follower->follow($user->id);
        return back();
    }
}

**public function unfollow(User $user)**
{
    #自分
    $follower = auth()->user();
#フォローしているか確かめる
    $is_following = $follower->isFollowing($user->id);
    #フォロー解除する
    if($is_following){
        $follower->unfollow($user->id);
        return back();
    }
}

### app/Models/User.php

**public function followers()**
{
    return $this->belongsToMany(self::class,'followers','followed_id','following_id');
}

**public function follows()**
{
    return $this->belongsToMany(self::class, 'followers', 'following_id', 'followed_id');
}
#フォローする
**public function follow(Int $user_id)**
{
    return $this->follows()->attach($user_id);
}
#フォロー解除する
**public function unfollow(Int $user_id)**
{
    return $this->follows()->detach($user_id);
}
#フォローしているか
**public function isFollowing(Int $user_id)**
{
    return (boolean) $this->followers()->where('following_id',$user_id)->first(['id']);
}
#フォローされているか
**public function isFollowed(Int $user_id)**
{
    return (boolean) $this->followers()->where('followed_id'.$user_id)->first(['id']);
}

### 【わからないこと】

1. $is_following = $follower->isFollowing($user->id);
この$user->idは何か

2. return $this->follows()->attach($user_id);
この記述でfollowersテーブルのレコードが作成されるのは何故か

3. return (boolean) $this->followers()->where('following_id',$user_id)->first(['id']);
firstが必要なのは何故か

**Comment by takakd** [comment]
first参考
https://qiita.com/mpyw/items/7c7e8dc665584122a275

attach参考
https://readouble.com/laravel/5.5/ja/eloquent-relationships.html
