### ISSUE TITLE
PHPStormのプロファイル

### ISSUE THREAD

**Issue by takakd** [yukihamu1206/twitter#12]
@osakana9114 
PHPStormのフォーマットのCode Styleって何をお使いですか。
揃えておこうと思いました。

**Comment by osakana9114** [comment]
@takakd 
デフォルトのままなにもいじってないです！
[.editorconfig](https://github.com/yukihamu1206/twitter/blob/master/.editorconfig) があるのでこれに従っているはずです🤔？

**Comment by takakd** [comment]
なるほど。.editorconfigのプラグイン入っておらず認識していないだけかもしれませんね。
確認してみます。

**Comment by takakd** [comment]
@yukihamu1206 
phpstormで、editorconfigのプラグインをインストールしてみてくださいませんでしょうか。
コードフォーマットのズレが解消されるかと思います。
参考: https://pleiades.io/help/phpstorm/managing-plugins.html

**Comment by yukihamu1206** [comment]
@takakd  かしこまりました。

**Comment by osakana9114** [comment]
@takakd 
飯田さんの環境の設定で .editorconfig を出力して、プロジェクトにpushしてもらいました。
これでフォーマット基準が揃えられたとおもいます👌
