### ISSUE TITLE
3/3 わからなかったこと1

### ISSUE THREAD

**Issue by yukihamu1206** [yukihamu1206/twitter#3]
【わからないこと】
`The PUT method is not supported for this route. Supported methods: GET, HEAD.`

というエラーが出る。

【調べたこと】
調laravelはpostとgetしか対応していないことが原因のエラー
擬似フォームメソッドを使う必要があるらしい

https://teratail.com/questions/223447

https://readouble.com/laravel/5.8/ja/controllers.html

【やったこと】

自分が擬似フォームメソッドを使っていることを確認
ルーティングはput

 ```              
        <form method="POST" action="{{ url('users/' .$user->id) }}" enctype="multipart/form-data">
                     @csrf
                     @method('PUT')
```

何故エラーが解決しないのか

**Comment by takakd** [comment]
サイトの説明だけ見るとうまくいきそうですね。
私も手元で見てみます。

**Comment by osakana9114** [comment]
### 原因
`$user` をbladeにうまく渡せていなかったため😌

app/Http/Controllers/UsersController:edit()
```php
public function edit(User $user)
{
  return view('users.edit',['users' => '$user']);
}
```
resources/views/users/edit.blade.php のform actionが **/users** になっていて、これはGETしか受け付けないルートであるためメソッドエラー。
参考： https://readouble.com/laravel/5.8/ja/controllers.html

　
以下のように修正。
```php
public function edit(User $user)
{
  return view('users.edit',['user' => $user]);
}
```
