### ISSUE TITLE
【参考】モデル結合ルートについて

### ISSUE THREAD

**Issue by osakana9114** [yukihamu1206/twitter#5]
_resources/views/tweets/index.blade.php_
```html
<a href="{{ url('tweets/' .$timeline->id) }}"><i class="far fa-comment fa-fw"></i></a>
```

↑で例えば **tweets/1** にリクエストした場合、

_app/Http/Controllers/TweetsController.php_
```php
public function show(Tweet $tweet, Comment $comment)
{
  $user = auth()->user();
  $tweet = $tweet->getTweet($tweet->id);
  $comments = $comment->getComments($tweet->id);

  return view('tweets.show',[
      'user'=>$user,
      'tweet'=>$tweet,
      'comments'=>$comments
  ]);
}
```

↑の `$tweet` で id=1 の Tweetインスタンスが取れるのはなんでか

---
@yukihamu1206 
Laravelの [モデル結合ルート](https://readouble.com/laravel/5.8/ja/routing.html#route-model-binding) という仕組みによるものみたいです👩‍💻

> {user}パラメーターをApp\Userモデルへ結合しているため、Userインスタンスはルートへ注入されます。ですからたとえば、profile/1のリクエストでは、IDが1のUserインスタンスが注入されます。

**Comment by osakana9114** [comment]
まだまだ知らないことがたくさんあります・・👩‍💻

**Comment by yukihamu1206** [comment]
なんかすごい便利ですね:flushed:ありがとうございます！
